title: Build-A-Satellite
description: The BIRDS Open Source Project is a collection of starter resources and guides to help build your nation's space capacity.
theme: just-the-docs

url: https://birdsopensource.github.io/docs/

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/birds-logo-light.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2015-2024 Laboratory of Lean Satellite Enterprises and In-Orbit Experiment. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/BIRDSOpenSource/docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Define Jekyll collections
collections:
  # Define a collection named "project-managers", its documents reside in the "_project-managers" directory
  project-managers:
    permalink: "/:collection/:path/"
    output: true
  
  obc-members:
    permalink: "/:collection/:path/"
    output: true
  
  eps-members:
    permalink: "/:collection/:path/"
    output: true
  
  com-members:
    permalink: "/:collection/:path/"
    output: true
  
  adcs-members:
    permalink: "/:collection/:path/"
    output: true

  structure-members:
    permalink: "/:collection/:path/"
    output: true

  resources:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "project-managers" collection
    project-managers:
      # Give the collection a name
      name: For Project Managers
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true

    # Reference the "obc-members" collection
    obc-members:
      name: For OBC Team Members
      nav_fold: true  

    # Reference the "eps-members" collection
    eps-members:
      name: For EPS Team Members
      nav_fold: true  

    # Reference the "com-members" collection
    com-members:
      name: For COM Team Members
      nav_fold: true  

    # Reference the "adcs-members" collection
    adcs-members:
      name: For ADCS Team Members
      nav_fold: true

    # Reference the "structure-members" collection
    structure-members:
      name: For Structure Team Members
      nav_fold: true  

    # Reference the "resources" collection
    resources:
      name: Resources
      nav_fold: true  