title: BIRDS-OSP
description: The BIRDS Open Source Project is a collection of starter resources and guides to help build your nation's space capacity.
theme: just-the-docs

url: https://birdsopensource.github.io/docs/

